[debug]
    # Log Level: [ Off | Error | Warn | Info | Debug | Trace ]
    log_level = "Warn"

    # Keep the log file after quitting Alacritty.
    persistent_logging = false

    # Print all received window events.
    print_events = false

    # Record all characters and escape sequences as test data.
    ref_test = false

    # Display the time it takes to redraw each frame.
    render_timer = false
