#!/usr/bin/env sh

# Space Names {{{
yabai -m space 1 --label code
yabai -m space 2 --label www
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label music
yabai -m space 8 --label meet
yabai -m space 9 --label irc
yabai -m space 10 --label mail
# }}}

# Layout {{{
yabai -m config layout bsp
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# New splits to right & bottom.
yabai -m config window_placement second_child
# }}}

# Focus {{{
yabai -m config focus_follows_mouse         off
yabai -m config mouse_follows_focus         off
yabai -m config window_topmost off
# yabai -m config window_shadow               float # on
# }}}

# Appearance {{{
yabai -m config external_bar                off:40:0
yabai -m config menubar_opacity             1.0
yabai -m config window_origin_display       default
yabai -m config window_zoom_persist         on
yabai -m config window_animation_duration   0.0
yabai -m config window_animation_easing     ease_out_circ
yabai -m config insert_feedback_color       0xffd75f5f
yabai -m config split_type                  auto
# yabai -m config focused_border_skip_floating  1
yabai -m config window_opacity              off
yabai -m config window_opacity_duration     0.00
yabai -m config active_window_opacity       1.0
# yabai -m config normal_window_opacity       0.97 # 0.90
# yabai -m config window_border               on | off

## Padding between all windows and the outer window border.
yabai -m config top_padding                 1 # 12
yabai -m config bottom_padding              1 # 12
yabai -m config left_padding                1 # 12
yabai -m config right_padding               1 # 12

## Padding between the individual windows.
yabai -m config window_gap                  1 # 06
# }}}

# Mouse Control {{{
yabai -m config mouse_drop_action           swap
yabai -m config mouse_modifier              ctrl # fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
# }}}

# Programs to ignore {{{
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
# }}}

# Limelight addon (Kill it and start it each time Yabai starts)
# killall limelight &>/dev/null
# limelight &>/dev/null &

# signals
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
#yabai -m signal --add event=space_changed action="yabai -m window --focus $(yabai -m query --windows --window | jq ".id")"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

#testing signals
# yabai -m signal --add event=window_destroyed action="terminal-notifier -message 'window_destroyed'"
# yabai -m signal --add event=application_terminated action="terminal-notifier -message 'application_terminated'"

echo "yabai configuration loaded.."
