export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export NPM_CONFIG_INIT_MODULE="${XDG_CONFIG_HOME}/npm/config/npm-init.js"
export NPM_CONFIG_TMP="${XDG_RUNTIME_DIR}/npm"

export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export NPM_CACHE_HOME="${XDG_CACHE_HOME}/npm"
