# This duplicates the `zsd` function but I don't
# want to source the functions here.
foreach conf (${ZDOTDIR}/env.d/**/*.zsh)
  source ${conf}
end
unset conf

[ -f ${ZSH_LOCAL_HOME}/zshenv ] && . ${ZSH_LOCAL_HOME}/zshenv || true
