# This duplicates the `zsd` function but I don't
# want to source the functions here.
foreach conf (${ZDOTDIR}/env.d/**/*.zsh)
  source ${conf}
end
unset conf

LOCAL_CFG=${XDG_CONFIG_LOCAL_HOME:-~/.local/config/}/zsh/zshenv
[ -f ${LOCAL_CFG} ] && . ${LOCAL_CFG}
